<a href="https://colab.research.google.com/github/hae-song/python-lecture/blob/main/d03_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%run my_init.py

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%matplotlib inline
#정적그래프를 그릴때 사용하는 옵션

#데이터 준비하기

In [ ]:
bream_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0]
bream_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0]

In [ ]:
smelt_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
smelt_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [ ]:
length = bream_length + smelt_length
weight = bream_weight + smelt_weight

In [ ]:
fish_data = [(l,w) for l,w in zip(length, weight)]

In [ ]:
fish_target = [1]*35 + [0]*14
#도미: 35개, 빙어:14개

In [ ]:
train_input = fish_data[0:35:1] #start:end:step
train_target = fish_target[0:35:1]
test_input = fish_data[35:]
test_target = fish_data[35:]
#연습과 테스트 데이터로 나누기

##훈련하기

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

kn = KNeighborsClassifier()
kn.fit(train_input, train_target) #학습, 한번은 해줘야함

#평가하기

In [ ]:
#kn.score(test_input, test_target)
accuracy_score(test_target, kn.predict(test_input))

0.7142857142857143

#numpy 연습

In [ ]:
import numpy as np

In [ ]:
np.random.seed(42)
X=np.random.randint(1,100,15).reshape(3,-1) #3행5열
X
#시드를 지정해줬기 때문에 결과가 항상 같아야한다.

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75],
       [88, 24,  3, 22, 53]])

In [ ]:
X.sum()

824

In [ ]:
X.sum(axis=0)
#열에 대한 합
#axis=1 : 행에 대한 값

array([161, 200, 105, 169, 189])

#샘플링 편향 해결하기

In [ ]:
np.random.seed(42)
index = np.arange(49)
index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [ ]:
np.random.shuffle(index)  #객체를 변경하는 메소드
index

array([29, 39, 47, 42,  7, 10, 24, 20, 12, 13, 46, 11, 38, 21, 16, 17, 30,
        1, 34, 36,  9, 33, 43, 48,  3,  6, 22, 18, 19, 35,  4, 28, 41,  5,
       23, 27, 14, 44, 37, 40,  8,  2, 25, 26, 32, 15, 45,  0, 31])

In [ ]:
input_arr = np.array(fish_data)
target_arr = np.array(fish_target)
#array로 변환

In [ ]:
train_input = input_arr[index[:35]]
train_target = target_arr[index[:35]]
test_input = input_arr[index[35:]]
test_target = target_arr[index[35:]]

In [ ]:
train_input.shape, train_target.shape

((35, 2), (35,))

In [ ]:
test_input.shape, test_target.shape

((14, 2), (14,))

In [ ]:
%matplotlib notebook
plt.scatter(train_input[:,0],train_input[:,1])
plt.scatter(test_input[:,0],test_input[:,1])

plt.xlabel('length')
plt.ylabel('weight')
plt.legend(['train','test'])


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
kn.fit(train_input, train_target)
kn.score(test_input, test_target)

1.0

In [ ]:
accuracy_score(test_target, kn.predict(test_input))

1.0

###Quartile Range

In [ ]:
np.random.seed(42)
arr = np.random.randint(1,101,100)  #100개의 데이터
arr

array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88, 100,  24,
         3,  22,  53,   2,  88,  30,  38,   2,  64,  60,  21,  33,  76,
        58,  22,  89,  49,  91,  59,  42,  92,  60,  80,  15,  62,  62,
        47,  62,  51,  55,  64,   3,  51,   7,  21,  73,  39,  18,   4,
        89,  60,  14,   9,  90,  53,   2,  84,  92,  60,  71,  44,   8,
        47,  35,  78,  81,  36,  50,   4,   2,   6,  54,   4,  54,  93,
        63,  18,  90,  44,  34,  74,  62, 100,  14,  95,  48,  15,  72,
        78,  87,  62,  40,  85,  80,  82,  53,  24])

In [ ]:
Q=np.percentile(arr,[25,50,75])  #arr 데이터의 25%, 50%, 75%값 반환
Q

array([23.5, 54. , 76.5])

In [ ]:
q1,q2,q3 = Q[0],Q[1],Q[2]

In [ ]:
IQR = q3-q1

이상치찾기

In [ ]:
#low fence
lfence = q1-1.5*IQR
lfence

-56.0

In [ ]:
#upper fence
ufence = q3+1.5*IQR
ufence

156.0

In [ ]:
arr[30] = 200

In [ ]:
arr < lfence

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr > ufence

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
(arr < lfence) | (arr > ufence)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
outliers = arr[(arr < lfence) | (arr>ufence)]
#수식 자체가 인덱스가 될 수있다.
outliers
#현재 없음.


array([200])

In [ ]:
#이상치를 뺀 결과값들
normal = arr[(arr > lfence) & (arr <= ufence)]
normal

array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88, 100,  24,
         3,  22,  53,   2,  88,  30,  38,   2,  64,  60,  21,  33,  76,
        58,  22,  89,  49,  59,  42,  92,  60,  80,  15,  62,  62,  47,
        62,  51,  55,  64,   3,  51,   7,  21,  73,  39,  18,   4,  89,
        60,  14,   9,  90,  53,   2,  84,  92,  60,  71,  44,   8,  47,
        35,  78,  81,  36,  50,   4,   2,   6,  54,   4,  54,  93,  63,
        18,  90,  44,  34,  74,  62, 100,  14,  95,  48,  15,  72,  78,
        87,  62,  40,  85,  80,  82,  53,  24])